import {
  CORE_AMMO,
  CORE_APPAREL,
  CORE_ARMOR,
  CORE_CHEMS,
  CORE_FOOD,
  CORE_OTHER_CONSUMABLES,
  CORE_POWER_ARMOR,
  CORE_WEAPONS,
} from "./sourceTruthData.js";

function normalizeText(value) {
  return String(value || "").trim();
}

function slugify(value) {
  return String(value || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function parseCompendiumUuid(uuid) {
  const match = String(uuid || "").match(/^Compendium\.([^.]+\.[^.]+)\.Item\.([A-Za-z0-9]+)$/);
  if (!match) return null;
  return { documentCollection: match[1], documentId: match[2] };
}

function uniqByDocument(rows) {
  const seen = new Set();
  const out = [];
  for (const row of rows) {
    const ref = parseCompendiumUuid(row?.foundryUuid);
    if (!ref) continue;
    const key = `${ref.documentCollection}:${ref.documentId}`;
    if (seen.has(key)) continue;
    seen.add(key);
    out.push({ ...row, ...ref });
  }
  return out;
}

const BEVERAGE_KEYWORDS = [
  "water",
  "cola",
  "nuka",
  "beer",
  "ale",
  "bourbon",
  "vodka",
  "whiskey",
  "wine",
  "rum",
  "gin",
  "moonshine",
  "coffee",
  "tea",
  "juice",
  "milk",
  "soda",
];

function isBeverage(entry) {
  const hay = `${normalizeText(entry?.label)} ${normalizeText(entry?.effect)}`.toLowerCase();
  return BEVERAGE_KEYWORDS.some((kw) => hay.includes(kw));
}

function buildCategoryRows() {
  const beverages = CORE_FOOD.filter(isBeverage);
  const foods = CORE_FOOD.filter((entry) => !isBeverage(entry));

  return {
    weapons: CORE_WEAPONS,
    ammunition: CORE_AMMO,
    armor: [...CORE_ARMOR, ...CORE_POWER_ARMOR],
    clothing: CORE_APPAREL,
    chems: CORE_CHEMS,
    food: foods,
    beverages,
    other: CORE_OTHER_CONSUMABLES,
  };
}

function buildTableDefinitions() {
  const categories = buildCategoryRows();

  const tableOrder = [
    "weapons",
    "ammunition",
    "armor",
    "clothing",
    "chems",
    "food",
    "beverages",
    "other",
  ];

  const tables = [];

  for (const category of tableOrder) {
    const rows = uniqByDocument(categories[category] || [])
      .sort((a, b) => normalizeText(a.label).localeCompare(normalizeText(b.label)));

    if (!rows.length) continue;

    const results = rows.map((entry, index) => ({
      description: normalizeText(entry.label) || "Unknown Item",
      type: "document",
      weight: 1,
      range: [index + 1, index + 1],
      documentCollection: entry.documentCollection,
      documentId: entry.documentId,
    }));

    const prettyCategory = category.charAt(0).toUpperCase() + category.slice(1);
    tables.push({
      category,
      name: `WA Loot - ${prettyCategory}`,
      description: `Generated by Wasteland Architect (${prettyCategory} loot table).`,
      formula: `1d${results.length}`,
      replacement: true,
      displayRoll: false,
      img: "icons/svg/d20-grey.svg",
      results,
    });
  }

  return tables;
}

export function exportFoundryScavengingImportScript() {
  const tables = buildTableDefinitions();
  const generatedAt = new Date().toISOString();
  const junkCsvUrl = "https://docs.google.com/spreadsheets/d/1S0bJBIzJ7DKIKmHl8Oj0WbdlKOAVJXAjUCKc3wxCQ1I/export?format=csv&gid=0";

  return `/* eslint-disable no-undef */
// Wasteland Architect - Foundry Fallout Scavenging RollTable Import
// Generated: ${generatedAt}
// Run this as a Script Macro in Foundry VTT while logged in as GM.
// It will create/update roll tables, import the WA Loot - Junk table from Google Sheets,
// and set Fallout scavenging category table mappings.

(async () => {
  const SYSTEM_ID = "fallout";
  const FOLDER_NAME = "Wasteland Architect - Loot Tables";
  const JUNK_TABLE_NAME = "WA Loot - Junk";
  const JUNK_TABLE_CSV_URL = "${junkCsvUrl}";
  const TABLES = ${JSON.stringify(tables, null, 2)};

  function parseCsvLine(line) {
    const cells = [];
    let cell = "";
    let inQuotes = false;
    for (let i = 0; i < line.length; i += 1) {
      const ch = line[i];
      if (ch === '"') {
        if (inQuotes && line[i + 1] === '"') {
          cell += '"';
          i += 1;
        } else {
          inQuotes = !inQuotes;
        }
      } else if (ch === "," && !inQuotes) {
        cells.push(cell);
        cell = "";
      } else {
        cell += ch;
      }
    }
    cells.push(cell);
    return cells;
  }

  function parseCsv(text) {
    return String(text || "")
      .split(/\\r?\\n/)
      .map((line) => parseCsvLine(line));
  }

  function yn(value) {
    return String(value || "").trim().toUpperCase();
  }

  function buildJunkResults(csvText) {
    const rows = parseCsv(csvText);
    const items = [];
    for (const row of rows) {
      const junk = String(row[0] || "").trim();
      const common = yn(row[1]);
      const uncommon = yn(row[3]);
      const rare = yn(row[5]);
      const weight = String(row[7] || "").trim();
      const notes = String(row[8] || "").trim();
      if (!junk) continue;
      if (junk.toLowerCase() === "junk") continue;
      if (junk.toLowerCase().includes("fallout 2d20 junk table")) continue;
      if (!["Y", "N"].includes(common) || !["Y", "N"].includes(uncommon) || !["Y", "N"].includes(rare)) continue;

      const materialTags = [];
      if (common === "Y") materialTags.push("C");
      if (uncommon === "Y") materialTags.push("U");
      if (rare === "Y") materialTags.push("R");

      const detailBits = [];
      if (materialTags.length) detailBits.push(\`Materials: \${materialTags.join("/")}\`);
      if (weight) detailBits.push(\`Weight: \${weight}\`);
      if (notes) detailBits.push(\`Notes: \${notes}\`);
      const description = detailBits.length ? \`\${junk} | \${detailBits.join(" | ")}\` : junk;

      items.push(description);
    }

    return items.map((description, index) => ({
      type: "text",
      text: description,
      description,
      img: "icons/svg/d20-black.svg",
      weight: 1,
      range: [index + 1, index + 1],
      drawn: false,
      flags: {},
    }));
  }

  if (!game?.user?.isGM) {
    ui.notifications.error("GM permissions are required to import scavenging tables.");
    return;
  }

  if (!game.system || game.system.id !== SYSTEM_ID) {
    ui.notifications.error("This importer is intended for the Fallout system.");
    return;
  }

  let folder = game.folders.find((f) => f.type === "RollTable" && f.name === FOLDER_NAME);
  if (!folder) {
    folder = await Folder.create({ name: FOLDER_NAME, type: "RollTable", color: "#6a9aba" });
  }

  async function upsertTable(payload) {
    let doc = game.tables.find((t) => t.name === payload.name);
    if (doc) {
      await doc.update(payload, { diff: false, recursive: false });
      return game.tables.get(doc.id);
    }
    return RollTable.create(payload);
  }

  const createdByCategory = {};

  for (const table of TABLES) {
    const results = table.results.map((r) => ({
      type: "document",
      text: "",
      description: r.description,
      img: "icons/svg/d20-black.svg",
      weight: r.weight ?? 1,
      range: r.range,
      drawn: false,
      documentCollection: r.documentCollection,
      documentId: r.documentId,
      flags: {},
    }));

    const payload = {
      name: table.name,
      description: table.description || "",
      formula: table.formula,
      replacement: table.replacement !== false,
      displayRoll: !!table.displayRoll,
      img: table.img || "icons/svg/d20-grey.svg",
      folder: folder?.id ?? null,
      results,
      ownership: { default: 0 },
      flags: {},
    };

    const doc = await upsertTable(payload);
    createdByCategory[table.category] = doc.uuid;
  }

  try {
    const response = await fetch(JUNK_TABLE_CSV_URL);
    if (!response.ok) throw new Error(\`HTTP \${response.status}\`);
    const csvText = await response.text();
    const junkResults = buildJunkResults(csvText);

    if (junkResults.length > 0) {
      const junkPayload = {
        name: JUNK_TABLE_NAME,
        description: "Generated by Wasteland Architect from the Fallout 2d20 junk spreadsheet. Journal references may call this the 2d20 Junk Table.",
        formula: \`1d\${junkResults.length}\`,
        replacement: true,
        displayRoll: false,
        img: "icons/svg/d20-grey.svg",
        folder: folder?.id ?? null,
        results: junkResults,
        ownership: { default: 0 },
        flags: {
          wastelandArchitect: {
            source: "google-sheet",
            csvUrl: JUNK_TABLE_CSV_URL,
            rollHint: "Use table roll (1dN) or map 2d20 as (d1-1)*20 + d2.",
          },
        },
      };
      const junkDoc = await upsertTable(junkPayload);
      createdByCategory.junk = junkDoc.uuid;
    } else {
      ui.notifications.warn("Junk table import found no valid rows in the spreadsheet.");
    }
  } catch (err) {
    console.warn("[Wasteland Architect] Junk table import failed:", err);
    ui.notifications.warn("Scavenging tables imported, but junk table import failed. Check sheet visibility/network.");
  }

  const existing = game.settings.get(SYSTEM_ID, "scavengingCategoryTables") || {};
  const merged = { ...existing, ...createdByCategory };
  await game.settings.set(SYSTEM_ID, "scavengingCategoryTables", merged);
  await game.settings.set(SYSTEM_ID, "scavengingCompendium", "");

  const configured = Object.entries(createdByCategory)
    .map(([k, v]) => \`\${k}: \${v}\`)
    .join("\\n");

  console.log("[Wasteland Architect] Scavenging tables configured:\\n" + configured);
  ui.notifications.info(\`Imported \${Object.keys(createdByCategory).length} scavenging loot tables.\`);
})();
`;
}

export function getFoundryScavengingScriptFilename() {
  const date = new Date().toISOString().slice(0, 10);
  return `fvtt-scavenging-rolltable-import-${date}.js`;
}

export function getFoundryScavengingTableSummary() {
  const tables = buildTableDefinitions();
  return tables.map((table) => ({
    category: table.category,
    name: table.name,
    entries: table.results.length,
  }));
}
